image: python:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: "demodb"
  MYSQL_ROOT_PASSWORD: "root"


before_script:
  - python -V
  - pip install -r requirements.txt
  

test:
  stage: test
  script:
  - python demoapp/manage.py makemigrations
  - python demoapp/manage.py migrate
  - python demoapp/manage.py runscript -v2 create_superuser
  - python demoapp/manage.py test
  

