image: python:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "demodb"
  MYSQL_ROOT_PASSWORD: "root"

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  script:
  - python manage.py test --settings django-practice-app.settings.ci
